### PR TITLE
Implement quick fixes for Rubocop

### PR DESCRIPTION
**Pull request by Verseth**
Hi, I implemented quick fixes for Rubocop warnings.

My team has been longing for a feature like this for quite some time.
So I'd decided to try and implement it myself.

And if I may say so myself, it came together pretty nicely.

Auto-correctable cop:

Rubocop Quick Fix Tooltip - Correctable

Rubocop Quick Fix List - Correctable

Uncorrectable cop:

Rubocop Quick Fix Tooltip - Uncorrectable

Rubocop Quick Fix List - Uncorrectable

Here's a demo:

Rubocop Quick Fixes Demo

### CODE REVIEW

**Comment by garbusbeach** [comment]
OMG, waiting for it whole life! 🔥

**Comment by cub8** [comment]
Finally we will have easy quick fixes, kudos to you 👏

**Comment by faramund** [comment]
@Verseth great feature!

**Comment by LoranKloeze** [comment]
Very nice! Will check it and release it in a new version somewhere this week I hope.

**Comment by LoranKloeze** [comment]
New release with this functionality is now published to the marketplace in version 0.9.3. Thank you very much for this PR!

**Comment by ukrmaxim** [comment]
Need help. Indicates that there are no quick fixes available. Reinstalled several times. Ubuntu 22.04. VSCode 1.74.3

**Comment by Verseth** [comment]
@ukrmaxim Looks like you've either got an old version of this extension or you've installed a different extension with similar functionality. The output has a different format.
image

**Comment by ukrmaxim** [comment]
@Verseth  Version 0.9.4 Installed from under VSCode. Before that, there was a ruby_rubocop plugin. I think this is the problem. But it has already been removed. On another laptop, where ruby-rubocop-revived was immediately installed, everything works. Different extension with similar functionality not installed.

**Comment by ukrmaxim** [comment]
@Verseth  thanks.

**Pull request merged**
